function action(label, color = '#3f3f46') { const button = document.createElement('button'); button.type = 'button'; button.textContent = label; button.style.cssText = `border:0;border-radius:8px;background:${color};color:#fff;padding:7px 9px;cursor:pointer;font-size:11px;font-weight:700;`; return button; }

export function renderEmojiFavoritesSettings(container, { context, refresh }) {
    const runtime = context?.emojiFavorites;
    if (!runtime) { container.textContent = 'Active la feature pour gérer les emojis favoris.'; return; }
    const description = document.createElement('div'); description.textContent = 'Affiche vos emojis les plus utilisés, ou une sélection manuelle, au-dessus du champ de discussion.'; description.style.cssText = 'font-size:12px;line-height:1.5;color:#a1a1aa;';
    const modeRow = document.createElement('label'); modeRow.style.cssText = 'display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:11px;color:#e4e4e7;font-size:12px;'; modeRow.append(document.createTextNode('Mode des favoris'));
    const mode = document.createElement('select'); mode.style.cssText = 'border:1px solid rgba(255,255,255,.16);border-radius:7px;background:#18181b;color:#fff;padding:7px 8px;'; for (const [value, label] of [['auto', 'Automatique'], ['manual', 'Manuel']]) { const option = document.createElement('option'); option.value = value; option.textContent = label; option.selected = runtime.getMode() === value; mode.append(option); } mode.addEventListener('change', () => { runtime.setMode(mode.value); refresh(); }); modeRow.append(mode);
    const limitRow = document.createElement('label'); limitRow.style.cssText = 'display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:10px;color:#e4e4e7;font-size:12px;'; limitRow.append(document.createTextNode('Nombre d’emojis affichés'));
    const limit = document.createElement('input'); limit.type = 'number'; limit.min = '0'; limit.max = '9'; limit.step = '1'; limit.value = String(runtime.getLimit()); limit.style.cssText = 'width:64px;border:1px solid rgba(255,255,255,.16);border-radius:7px;background:#18181b;color:#fff;padding:7px 8px;text-align:center;'; limit.addEventListener('change', () => { runtime.setLimit(limit.value); limit.value = String(runtime.getLimit()); }); limitRow.append(limit);
    const help = document.createElement('div'); help.style.cssText = 'margin-top:10px;font-size:11px;line-height:1.45;color:#a1a1aa;'; help.textContent = runtime.getMode() === 'manual' ? 'Dans le picker emoji natif, Maj+clic ou Alt/⌘+clic ajoute ou retire un favori. Les favoris choisis sont encadrés en jaune.' : 'Les emojis sont classés selon leur fréquence et leur date d’utilisation.';
    const body = document.createElement('div'); body.style.cssText = 'margin-top:12px;';
    if (runtime.getMode() === 'manual') {
        const addRow = document.createElement('div'); addRow.style.cssText = 'display:flex;gap:7px;margin-bottom:10px;'; const value = document.createElement('input'); value.type = 'text'; value.placeholder = '😀 ou :nom_emoji:'; value.style.cssText = 'min-width:0;flex:1;border:1px solid rgba(255,255,255,.16);border-radius:7px;background:#18181b;color:#fff;padding:7px 8px;'; const add = action('Ajouter', '#2563eb'); add.addEventListener('click', () => { const result = runtime.toggleManual(value.value); runtime.toast(result.message, !result.ok); if (result.ok) refresh(); }); addRow.append(value, add); body.append(addRow);
        const favorites = runtime.getManual(); if (!favorites.length) { const empty = document.createElement('div'); empty.textContent = 'Aucun favori manuel.'; empty.style.cssText = 'font-size:12px;color:#a1a1aa;'; body.append(empty); } else { const list = document.createElement('div'); list.style.cssText = 'display:flex;flex-wrap:wrap;gap:6px;'; favorites.forEach((favorite, index) => { const item = document.createElement('div'); item.style.cssText = 'display:flex;align-items:center;gap:3px;border:1px solid rgba(251,191,36,.22);border-radius:8px;background:rgba(113,63,18,.16);padding:4px;'; const emoji = document.createElement('span'); emoji.textContent = favorite.insertText; emoji.title = favorite.insertText; emoji.style.cssText = 'min-width:25px;text-align:center;font-size:13px;'; const left = action('←'); left.disabled = index === 0; const right = action('→'); right.disabled = index === favorites.length - 1; const remove = action('×', '#7f1d1d'); left.addEventListener('click', () => { runtime.moveManual(index, -1); refresh(); }); right.addEventListener('click', () => { runtime.moveManual(index, 1); refresh(); }); remove.addEventListener('click', () => { runtime.removeManual(index); refresh(); }); item.append(emoji, left, right, remove); list.append(item); }); body.append(list); }
    } else {
        const usage = runtime.getUsage().sort((left, right) => right.count - left.count || right.lastUsedAt - left.lastUsedAt); const top = document.createElement('div'); top.textContent = usage.length ? `${usage.length} emoji${usage.length > 1 ? 's' : ''} mémorisé${usage.length > 1 ? 's' : ''}.` : 'Aucun emoji utilisé pour le moment.'; top.style.cssText = 'font-size:12px;color:#a1a1aa;'; const clear = action('Réinitialiser l’historique'); clear.style.marginTop = '8px'; clear.addEventListener('click', () => { if (!window.confirm('Réinitialiser l’historique des emojis utilisés ?')) return; runtime.clearUsage(); refresh(); }); body.append(top, clear);
    }
    container.append(description, modeRow, limitRow, help, body);
}
